/**
 * Regenerate packages/cli/src/skills-data.ts from the real sources:
 *   skills/*  → SKILL_FILES (installed by `bro setup --skills`)
 *   formulas/*.toml    → FORMULA_FILES (installed by `bro setup --beads`)
 *
 * The embedded copies are what the published tarball carries — repo-root
 * files are the single source of truth and this script keeps them in sync.
 * `--check` verifies the generated file is current without writing.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(fileURLToPath(import.meta.url), '..', '..')
const out = join(root, 'packages/cli/src/skills-data.ts')
const check = process.argv.includes('--check')

function collect(dir, prefix) {
  const files = {}
  // readdir order isn't guaranteed across filesystems — sort for a
  // deterministic generated file (--check compares byte-for-byte).
  const entries = readdirSync(join(root, dir), { recursive: true, withFileTypes: true })
    .sort((a, b) => join(a.parentPath, a.name).localeCompare(join(b.parentPath, b.name)))
  for (const entry of entries) {
    if (!entry.isFile()) {
      continue
    }
    const abs = join(entry.parentPath, entry.name)
    // POSIX keys — the generated file must be identical on every OS.
    files[`${prefix}${relative(join(root, dir), abs).replaceAll('\\', '/')}`] = readFileSync(abs, 'utf8')
  }
  return files
}

const skills = {}
for (const entry of readdirSync(join(root, 'skills'), { withFileTypes: true })
  .sort((a, b) => a.name.localeCompare(b.name))) {
  if (!entry.isDirectory()) {
    continue
  }
  for (const [rel, content] of Object.entries(collect(join('skills', entry.name), `${entry.name}/`))) {
    skills[rel] = content
  }
}
const formulas = collect('formulas', '')

const render = (files) =>
  Object.entries(files)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('\n')

const src = `// GENERATED by scripts/gen-embedded.ts — do not edit by hand.
// Sources: skills/*/ and formulas/ at the repo root.
export const SKILL_FILES: Record<string, string> = {
${render(skills)}
}

export const FORMULA_FILES: Record<string, string> = {
${render(formulas)}
}
`

if (check) {
  if (readFileSync(out, 'utf8') !== src) {
    console.error('skills-data.ts is stale — run scripts/gen-embedded.ts')
    process.exit(1)
  }
  console.error('skills-data.ts is current')
} else {
  writeFileSync(out, src, 'utf8')
  console.error(`skills-data.ts: ${Object.keys(skills).length} skill file(s), ${Object.keys(formulas).length} formula(s)`)
}
